#Copy NGINX scripts
- name: copy NGINX scripts
  copy:
    src: "{{ item }}"
    dest: /usr/bin/{{ item }}
    mode: 0755
    owner: root
    group: root
  with_items:
    - nginx-ha-setup
    - nginx-sync.sh
    - nginx-amplify-agent.py
  tags:
    - configure_nginx

#Copy NGINX sync file
- name: copy  NGINX sync file
  template:
    src: nginx-sync.conf.j2
    dest: /etc/nginx/nginx-sync.conf
    mode: 0644
    owner: root
    group: root
  tags:
    - configure_nginx

- name: Create a 2048-bit SSH key for root ~root/.ssh/id_rsa
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PermitRootLogin without-password'
  notify: reload SSH