---
- name: Install Epel
  yum: name={{ item }} state=present
  with_items:
   - epel-release

- name: Enable erlang repo
  copy:
    src: rabbitmq-erlang.repo
    dest: /etc/yum.repos.d/rabbitmq-erlang.repo
    owner: root
    group: root
    mode: 0644
   
- name: install |  install erlang
  yum: 
    name: erlang
    state: present

- name: install |  install rpm
  yum: name=/opt/ansible_rabbitmq/{{ item }}  state=present
  with_items: 
   - rabbitmq-server-3.7.6-1.el7.noarch.rpm
   #- erlang-19.2.0-1.el6.x86_64.rpm
   
  
- name: install |  ensure service running and onboot
  service: name=rabbitmq-server state=started enabled=yes

- name: install |  enabled plugins
  rabbitmq_plugin: name={{ item }} state=enabled
  with_items:
    - "{{ rabbitmq_plugins }}"

- name: ensure the default vhost contains the HA policy via a dict
  rabbitmq_policy: name=HA pattern='.*'
  args:
    tags:
     "ha-mode": all

