---

- name: CENTOS-BMP | Updating packages
  action: yum name=* state=latest

- name: CENTOS-BMP | Installing additional packages
  action: yum pkg={{ item }} state=installed
  with_items:
     - bc
     - git
     - vim
     - man
     - ntp
     - tmux
     - tree
     - nano
     - curl
     - wget
     - htop
     - whois
     - unzip
     - screen
     - net-tools
     - yum-utils
     - bash-completion

- name: CENTOS-BMP | Purging old kernels
  command: package-cleanup --oldkernels --count=2 -y
  changed_when: False

- name: CENTOS-BMP | Cleaning yum cache
  command: yum clean all
  changed_when: False

- name: CENTOS-BMP | Uploading administrative bash profile
  template: src=bash_profile dest=/root/.bash_profile owner=root group=root mode=0600

- name: CENTOS-BMP | Setting up administrative bash profile
  template: src=bashrc dest=/root/.bashrc owner=root group=root mode=0600

- name: CENTOS-BMP | Setting up locale - LANG
  lineinfile: dest=/etc/environment regexp="LANG=en_US.utf-8" line="LANG=en_US.utf-8"

- name: CENTOS-BMP | Setting up locale - LC_ALL
  lineinfile: dest=/etc/environment regexp="LC_ALL=en_US.utf-8" line="LC_ALL=en_US.utf-8"

- name: CENTOS-BMP | Setting up swappiness ratio
  sysctl:
    name: vm.swappiness
    value: 10
    sysctl_set: yes
    state: present
    reload: yes

- name: CENTOS-BMP | Setting up delayed memory pages flushing
  sysctl:
    name: vm.dirty_ratio
    value: 60
    sysctl_set: yes
    state: present
    reload: yes

- name: CENTOS-BMP | Setting up delayed flushing buffer size
  sysctl:
    name: vm.dirty_background_ratio
    value: 2
    sysctl_set: yes
    state: present
    reload: yes

- name: CENTOS-BMP | Setting up memory manager
  sysctl:
    name: vm.min_free_kbytes
    value: 131072
    sysctl_set: yes
    state: present
    reload: yes

- name: CENTOS-BMP | Setting up allowed port range
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: 2000 65000
    sysctl_set: yes
    state: present
    reload: yes

- name: CENTOS-BMP | Setting up socket receive buffer
  sysctl:
    name: net.core.rmem_max
    value: 16777216
    sysctl_set: yes
    state: present
    reload: yes

- name: CENTOS-BMP | Setting up socket send buffer
  sysctl:
    name: net.core.wmem_max
    value: 16777216
    sysctl_set: yes
    state: present
    reload: yes

- name: CENTOS-BMP | Tuning TCP receive buffer limit
  sysctl:
    name: net.ipv4.tcp_rmem
    value: 4096 87380 16777216
    sysctl_set: yes
    state: present
    reload: yes

- name: CENTOS-BMP | Tuning TCP send buffer limit
  sysctl:
    name: net.ipv4.tcp_wmem
    value: 4096 65536 16777216
    sysctl_set: yes
    state: present
    reload: yes

- name: CENTOS-BMP | Limiting app incoming connection backlog
  sysctl:
    name: net.core.somaxconn
    value: 4096
    sysctl_set: yes
    state: present
    reload: yes

- name: CENTOS-BMP |Increasing NIC buffer size
  sysctl:
    name: net.core.netdev_max_backlog
    value: 16384
    sysctl_set: yes
    state: present
    reload: yes

- name: CENTOS-BMP | Increasing number of remembered/cached connections
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 8192
    sysctl_set: yes
    state: present
    reload: yes
