#! /bin/sh
#
# freeram_p.sh
# Copyright (C) 2017 Stefano Stella <mprenditore@gmail.com>
#
# Distributed under terms of the MIT license.
# 
# freeram_p - print free ram percentage


free | grep Mem | awk '{print $7/$2*100}' | cut -d'.' -f1
